### ISSUE TITLE
On the vitsi.ai deployed environment email verification link points to localhost:9091

### ISSUE THREAD

**Issue by nikasakandelidze** [oseducation/knowledge-graph#383]
# Problem
Upon registering in the app and receiving verification email ( Image 1 ), verify email anchor tag points to: localhost:9091 ( image 2 ) and for successful completion had to update url by hand to point to vitsti.ai.

<img width="705" alt="image" src="https://github.com/oseducation/knowledge-graph/assets/60848556/c98dc64e-e47b-4cbf-a98f-8e4b0d5bfc74">

<img width="820" alt="Screenshot 2023-09-26 at 10 47 31" src="https://github.com/oseducation/knowledge-graph/assets/60848556/c80d7463-4d50-4201-bfa4-8bf338324cbe">

# Cause
As i noticed in the docker image build step config.json is simply being copied from: server/config/config.json where SiteURL: localhost:9091 which is used in whole server and this value is not dynamic ( ex: passing via env variables ).

<img width="431" alt="image" src="https://github.com/oseducation/knowledge-graph/assets/60848556/d13c1a02-35c7-4824-a3a9-c0bb62404122">

# Potential Solution
Some of the informations in config.json including SiteURL needs to be dynamic and not concrete until the actual server side container starts running, at which point we can inject variables via kubernetes deployment manifest file ( via env variables ? ). This will also make a good case for the future if multiple env-s are present

Thanks in advance and would love to share your opinions.
P.S. Great Project btw.

**Comment by iomodo** [comment]
Thanks a lot for the bug report @nikasakandelidze 
We are on it :)
