### ISSUE TITLE
Implement Top Performers

### ISSUE THREAD

**Issue by iomodo** [oseducation/knowledge-graph#448]
Implement Top Performers backend tie up with front

1. On the backend just perform a single query to the db to collect top 10 performers, who have finished the most number of topics. Notice that you should return top performers by language.

2. Implement the Top performers in the front end. The component should not make the whole page scroll, instead make the component scrollable (if needed).

To view the current UI you can visit `/dashboard`

**Comment by divyaK15** [comment]
Hello! 

I’m one of Meriam’s teammates and we were able to build and run Vitisi AI locally, so we’re ready to start contributing 🥳Could we get assigned this issue please?

Thanks,
Divya

**Comment by iomodo** [comment]
Hey Divya, so wonderful to hear that! 🚀

**Comment by divyaK15** [comment]
Hello!

Due to time constraints with our project, the team and I have decided to work on another issue instead (#455). Could I be unassigned from this issue please?

Thanks,
Divya
