### ISSUE TITLE
Rename Chat to AI Tutor

### ISSUE THREAD

**Issue by iomodo** [oseducation/knowledge-graph#470]
Rename `Chat` to `AI Tutor`

![Image](https://github.com/oseducation/knowledge-graph/assets/2340127/e92158e2-0fde-49b2-89a0-15d14a64b6c5)

visit `/dashboard`

**Comment by vinayakhegde1** [comment]
@iomodo May I work on this issue

**Comment by vinayakhegde1** [comment]
@iomodo Created PR on this if there is anything else please do let me know
