### ISSUE TITLE
Render old messages as links

### ISSUE THREAD

**Issue by iomodo** [oseducation/knowledge-graph#478]
In the chat, render old messages as links to resources. Texts should be rendered the same way, but message types like video or Karel IDE should be rendered as links. 
Only the last message should be rendered as a YouTube player or IDE.

Visit `AI Tutor` page to see the current UI

**Comment by nikasakandelidze** [comment]
@iomodo If this issue is free, I'll start with this.
Cheers.

**Comment by iomodo** [comment]
Wonderful @nikasakandelidze , let me know if you need anything <3

**Comment by nikasakandelidze** [comment]
#546
