### ISSUE TITLE
Forgot Password flow missing

### ISSUE THREAD

**Issue by nikasakandelidze** [oseducation/knowledge-graph#542]
I forgot my password to the platform and can't reset it.

**Comment by nikasakandelidze** [comment]
Will take this if it's ok with you.

**Comment by iomodo** [comment]
🚀

**Comment by iomodo** [comment]
Reassigning it to myself because of urgency. Thanks for taking a look @nikasakandelidze <3

**Comment by nikasakandelidze** [comment]
@iomodo sorry for taking forerver, will reengage soon with stuff.
Thanks for covering.
